name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: "build/"

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: ${{ secrets.HOME_PATH }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
